name: Build Image, push to Registry and Deploy to Digital Ocean's PRD

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
permissions: write-all
jobs:

          

  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: read-all
    
    steps:
      - uses: actions/checkout@master
        
      - name: execute docker-compose
        uses: appleboy/ssh-action@master
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CDN_NAME: ${{ secrets.CDN_NAME }}
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
          CDN_API_SECRET: ${{ secrets.CDN_API_SECRET }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2077
          script: |
            docker ps -a
